"""
Model mixins for DBSC session and challenge storage.

Usage in an existing Flask-SQLAlchemy app::

    from flask_dbsc.models import DBSCSessionMixin, DBSCChallengeMixin

    class DBSCSession(db.Model, DBSCSessionMixin):
        __tablename__ = 'dbsc_sessions'
        # Add any extra columns here, e.g. a FK to your User model:
        # user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    class DBSCChallenge(db.Model, DBSCChallengeMixin):
        __tablename__ = 'dbsc_challenges'

These classes are plain SQLAlchemy models — include them in your normal
Flask-Migrate / Alembic setup and they will appear in autogenerated migrations.
"""
from sqlalchemy import Column, Float, String, Text


class DBSCSessionMixin:
    """Columns required to store a DBSC-bound session key."""
    session_id    = Column(String(64),  primary_key=True)
    public_key    = Column(Text,         nullable=False)
    metadata_json = Column(Text)
    expires_at    = Column(Float,        nullable=False, index=True)


class DBSCChallengeMixin:
    """Columns required to store a one-time registration challenge."""
    challenge  = Column(String(64), primary_key=True)
    expires_at = Column(Float,      nullable=False)
